apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-tool
  namespace: default
data:
  hello.py: |
    import sys, json
    for line in sys.stdin:
        req = json.loads(line)
        if req.get("type") == "invoke" and req["tool"]["name"] == "hello":
            print(json.dumps({"type": "result", "content": "Hello World"}))
            sys.stdout.flush()
