apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: hello-mcp-server
  namespace: default
spec:
  transportType: stdio
  deployment:
    image: python:3.11-slim
    cmd: /bin/sh
    args:
      - -c
      - pip install mcp && python3 /tools/hello_mcp.py
    volumes:
      - name: tool-code
        configMap:
          name: hello-mcp-tool
    volumeMounts:
      - name: tool-code
        mountPath: /tools

