// Mock data for conflicts
export const mockConflicts = [
  {
    id: '1',
    rowNumber: 125,
    field: 'customer_id',
    sourceValue: 'CUST-2024-001',
    targetValue: 'CUST-2024-001',
    type: 'duplicate' as const,
    severity: 'high' as const,
    aiSuggestion: 'Keep the record with the most recent last_modified timestamp (Bank B record from 2024-10-03)',
    resolutionOptions: ['Keep Latest', 'Keep Bank A', 'Keep Bank B', 'Flag for Review'],
  },
  {
    id: '2',
    rowNumber: 342,
    field: 'date_of_birth',
    sourceValue: '1985-03-15',
    targetValue: '03/15/1985',
    type: 'format' as const,
    severity: 'medium' as const,
    aiSuggestion: 'Standardize all dates to ISO 8601 format (YYYY-MM-DD). Both values represent the same date.',
    resolutionOptions: ['Use ISO Format', 'Keep Bank A', 'Keep Bank B'],
  },
  {
    id: '3',
    rowNumber: 567,
    field: 'account_balance',
    sourceValue: '$45,230.50',
    targetValue: '45230.5',
    type: 'format' as const,
    severity: 'low' as const,
    aiSuggestion: 'Convert to decimal format without currency symbols for consistency (45230.50)',
    resolutionOptions: ['Normalize to Decimal', 'Keep Bank A', 'Keep Bank B'],
  },
  {
    id: '4',
    rowNumber: 789,
    field: 'email',
    sourceValue: 'john.smith@email.com',
    targetValue: 'j.smith@email.com',
    type: 'mismatch' as const,
    severity: 'high' as const,
    aiSuggestion: 'These appear to be different email addresses for the same person. Recommend manual review or contact validation.',
    resolutionOptions: ['Flag for Review', 'Keep Bank A', 'Keep Bank B', 'Merge Both'],
  },
  {
    id: '5',
    rowNumber: 891,
    field: 'phone_number',
    sourceValue: '(555) 123-4567',
    targetValue: '+1-555-123-4567',
    type: 'format' as const,
    severity: 'low' as const,
    aiSuggestion: 'Standardize to E.164 international format: +15551234567',
    resolutionOptions: ['Use E.164 Format', 'Keep Bank A', 'Keep Bank B'],
  },
  {
    id: '6',
    rowNumber: 1023,
    field: 'address',
    sourceValue: '123 Main St, New York, NY 10001',
    targetValue: '123 Main Street, New York, NY, 10001',
    type: 'format' as const,
    severity: 'low' as const,
    aiSuggestion: 'These are equivalent addresses with minor formatting differences. Standardize abbreviations.',
    resolutionOptions: ['Standardize Format', 'Keep Bank A', 'Keep Bank B'],
  },
];
